/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JNI */

#ifndef _Included_jni_JNI
#define _Included_jni_JNI
#ifdef __cplusplus
extern "C" {
#endif

 /*
 * Class:     jni_JNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_JNI_init
  (JNIEnv *, jclass);

/*
 * Class:     jni_JNI
 * Method:    process
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_JNI_process
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif